### ISSUE TITLE
Most things not working

### ISSUE THREAD

**Issue by FrogGoblin** [The-Grand-Archives/Elden-Ring-CT-TGA#104]
Npc menu's, item gib, and a bunch of other things not working as of 31/07/24

I understand that this is probably because of the latest patch and you're already well aware!!! if that is the case please just let me know and ignore this completely, just wanting to help out! tyvm for all you do <3

**Comment by inuNorii** [comment]
The only thing I haven't updated that needs updating is "Npc menus", everything else should be functional already since v1.14.1
