### ISSUE TITLE
Counter only

### ISSUE THREAD

**Issue by Croisade86** [The-Grand-Archives/Elden-Ring-CT-TGA#119]
Hi,
several streamers need a death counter only,
I haven't found an application of this type, but your tool can find the memory address of the game's deaths, so it should be possible to extract the game to create a counter.

I've tried to isolate this element myself, but it's not my area of expertise.
The idea is once isolated to create a small python or other to create a standalone counter without CE.

**Comment by inuNorii** [comment]
This isn't really what the issue tracker is for, but I'll try to give you an answer anyway.

Multiple applications have already been made for this.
The relevant information can be read from either `[GameDataMan]+0x94` or from somewhere in the save file.

**Comment by Croisade86** [comment]
The applications found on the net detect certain pixels on the screen when the message "you are dead" appears the counter increments but does not resume the history of previous deaths. Also the save editors do not bring out the value of the number of deaths in the game just the stats and advancements.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
