### ISSUE TITLE
Where is instant kill and/or damage at?

### ISSUE THREAD

**Issue by DarkAlchy** [The-Grand-Archives/Elden-Ring-CT-TGA#123]
Mod programs have both so I am sure they are in this somewhere, though I couldn't find them.

**Comment by inuNorii** [comment]
This is not an issue.

**Comment by DarkAlchy** [comment]
Might not be an issue but stupid to not plan it when we have other programs that does do it.  I guess they just have better devs, or something.

Thanks anyway.
