### ISSUE TITLE
[ERROR] Drawstring Freezing Grease

### ISSUE THREAD

**Issue by Granze** [The-Grand-Archives/Elden-Ring-CT-TGA#25]
Spawning it gives you an item called  `[ERROR] Drawstring Freezing Grease`. The item itself works as intended but is somehow not recognized in the proper category, in fact is placed at the bottom of the inventory and not close to the other items of the same type.

Other drawstring greases are fine.

**Comment by inuNorii** [comment]
The `[ERROR]` label is given to items not intended to be acquired in a regular playthrough.
Do not use items like that online.

**Comment by Granze** [comment]
I see, thanks.
