### ISSUE TITLE
Game crash everytime I use "AddSoul" under build creation

### ISSUE THREAD

**Issue by thickyvans** [The-Grand-Archives/Elden-Ring-CT-TGA#32]
As title says every time I try and use the Add Souls function in the table my game crashes regardless of amount. Turned off anti-virus in case that was the issue somehow to no avail.

**Comment by kaufman79** [comment]
Same thing happens to me

**Comment by thickyvans** [comment]
Super unfortunate, Glad to hear I'm not alone though
