### ISSUE TITLE
Unlock all Cookbooks does not give all cookbooks

### ISSUE THREAD

**Issue by mrj760** [The-Grand-Archives/Elden-Ring-CT-TGA#34]
I'm not sure if it's supposed to make everything craftable or actually put the cookbooks in your inventory, but not all the cookbooks are not in my inventory. It's easy to tell because they are numerically ordered.

**Comment by inuNorii** [comment]
The cookbook items are irrelevant and do nothing.
The script triggers the relevant events that unlock the crafting options.

**Comment by StabHackSlashKill** [comment]
I know this is closed but I experience this same thing with unlock all whetblades. I check the box and nothing happens.
