### ISSUE TITLE
Can´t find effigy´s options related (Summoning pools)

### ISSUE THREAD

**Issue by xCoNDex** [The-Grand-Archives/Elden-Ring-CT-TGA#36]
Cheat table allows to unlock all sites of grace for example, but can't figure out how to unlock Effigies of the Martyr, any help pls?

**Comment by inuNorii** [comment]
That's currently not a feature in the table.

**Comment by xCoNDex** [comment]
> That's currently not a feature in the table.

oh I see, any plans to add this in the future?

**Comment by inuNorii** [comment]
I've got event IDs for it, but they need more testing and documentation.

**Comment by xCoNDex** [comment]
> I've got event IDs for it, but they need more testing and documentation.

If I can serve you as a tester let me know, I will be delighted

**Comment by escape0707** [comment]
Is there any document for the event IDs? About which is which?
