### ISSUE TITLE
<<ccode section compilation failed:tcc: error undefined symbol 'CParamUtils_GetRowData'>>

### ISSUE THREAD

**Issue by isolvepracticalproblems** [The-Grand-Archives/Elden-Ring-CT-TGA#37]
ItemGib does not work when clicking on it, no anti-viruses are on and CheatEngine is whitelisted. When I open scripts, it gives me an error.

**Comment by inuNorii** [comment]
Post your error.

**Comment by isolvepracticalproblems** [comment]
![Screenshot error thingy](https://user-images.githubusercontent.com/28712605/211123912-9bf68b49-be9c-4fab-a27d-d7127e26d97d.png)



> Post your error.

**Comment by inuNorii** [comment]
Ah, it's that issue. Are you using an old or just generally slow CPU?
The Singleton Finder script is timing out and pretty much everything else in the cheat table depends on it having run properly.

Could you try opening the .CT file in a text editor, go to line 129830, and try to set the timeout value to something higher? Example: `{cscript timeout=2000}` -> `{cscript timeout=3000}`

In case your text editor doesn't have line numbers, you can ctrl+f for `"DLRuntimeCLass Singleton Finder &amp; Registerer"`.
