### ISSUE TITLE
MassItemsGib crashes/freezes

### ISSUE THREAD

**Issue by lologannus** [The-Grand-Archives/Elden-Ring-CT-TGA#43]
It crashes the game or it works but at 1 frame per minute, it seems very odd for example i gave myself all weapons, then i tried again to get all of them twice and it doesnt really crashes the game but the window is not responding anymore. It keeps doing it each time i want to try again.

**Comment by StabHackSlashKill** [comment]
I have also experienced games crashing when trying to give all weapons or give all armor
