### ISSUE TITLE
Im dumb plz help

### ISSUE THREAD

**Issue by NetunooOG** [The-Grand-Archives/Elden-Ring-CT-TGA#48]
Trying to install CE for first time and every time I try to use this CT it says I compiled CE wrong and need to reinstall it. Using Ver 7.5 using laz to compile in 64bit. Is that the problem? I cant find Ver 7.4 Of CE anywhere nor a table in 7.5. I already made mistake of not using the addon. was getting a error for about a hour till I installed it and got stuck here. At least i can build it now even if it says im doing it wrong (only when I try load CT) Plz help thx.

**Comment by inuNorii** [comment]
This is not an issue.

**Comment by NetunooOG** [comment]
Then Plz help im so confused why your CT wont work
