### ISSUE TITLE
Shop option crashes game

### ISSUE THREAD

**Issue by Britlandian** [The-Grand-Archives/Elden-Ring-CT-TGA#49]
title says it all, click open and game crashes

**Comment by inuNorii** [comment]
Sorry, I'm not sure why that's happening for you. It works for me and doesn't really do anything special.
Could you state your game version, cheat engine version, and cheat table version?
Do the "Level Up", "Rebirth", and "Cosmetics" menu scripts crash for you as well?

**Comment by inuNorii** [comment]
This might be fixed now.
