### ISSUE TITLE
Unlock all whetblades 

### ISSUE THREAD

**Issue by StabHackSlashKill** [The-Grand-Archives/Elden-Ring-CT-TGA#50]
When I check the box to unlock all whetblades, nothing happens. No events are triggered. I don't get the whetblades in my inventory. Nothing.

**Comment by inuNorii** [comment]
Events being triggered has no visual in-game.
The items are not needed, as they don't do anything at all.

Check if you got the actual functionality whetblades are supposed to have instead.
