### ISSUE TITLE
MassitemGib - all crafting materials 

### ISSUE THREAD

**Issue by b-kva** [The-Grand-Archives/Elden-Ring-CT-TGA#54]
Crafting materials appear only in storage. But I can't take them out, the game says the inventory is full. Inventory is empty and crafting menu shows 0 on all materials, but if I try to pick any material up, it drops on the ground saying that the inventory is full

**Comment by inuNorii** [comment]
Your inventory is full. There is a _total_ limit to separate item slots that can be used which is not separated by item type.
You probably have too many weapons or armour pieces.
