### ISSUE TITLE
How I can raise the amount of weight my character can carry to keep the load light?

### ISSUE THREAD

**Issue by NefistoSamael** [The-Grand-Archives/Elden-Ring-CT-TGA#60]
Hello everyone, does anyone know how I can raise the amount of weight my character can carry to keep the load light? I know it can be done by raising the green bar to 99, but I'm playing in offline mode so I want to enjoy a lot of heavy weapons with light load

**Comment by inuNorii** [comment]
Github issues are not for support questions.
This is not an issue.
