### ISSUE TITLE
Table scripts claim version 2.01

### ISSUE THREAD

**Issue by Zatharax** [The-Grand-Archives/Elden-Ring-CT-TGA#62]
Some scripts claim they're only available for version 2.01 of Elden Ring despite the description of the release claiming 2.02

![image](https://github.com/The-Grand-Archives/Elden-Ring-CT-TGA/assets/56146659/b5750a57-bf0a-48e7-8da6-c7c4f7deb9e9)

**Comment by inuNorii** [comment]
Those scripts have not been updated yet.

**Comment by Zatharax** [comment]
> Those scripts have not been updated yet.

Ah, understood.

**Comment by inuNorii** [comment]
Can keep the issue open for now, until they're updated
