### ISSUE TITLE
unlock all summoning pools not working

### ISSUE THREAD

**Issue by LineZer0z** [The-Grand-Archives/Elden-Ring-CT-TGA#70]
im using the latest version of CE and table im on the newest update of elden ring

**Comment by Kiriee** [comment]
I think I can't summon any of my spirit now after activating this

**Comment by healfear** [comment]
In my case it didnt work at all, all summoning pools remained unchecked as well.

**Comment by CerezaKitty** [comment]
Hope It's fixed soon, really wanna help people
