### ISSUE TITLE
DLC items not working

### ISSUE THREAD

**Issue by DLulzC** [The-Grand-Archives/Elden-Ring-CT-TGA#71]
I'm on Elden Ring patch 1.12.2 with Shadow of the Erdtree in my steam library and the newest version of the cheat table does not add any DLC items. Tested it on a new save file and the MassItemGib options only added the base game items.

**Comment by inuNorii** [comment]
MassItemGib has a specific section for DLC in it.
I'll keep this issue open for now, as the ItemGib dropdown does not have DLC items yet.
