### ISSUE TITLE
ItemGib Spawning Weapons with invalid Reinforcement levels.

### ISSUE THREAD

**Issue by ZINK-ZINK** [The-Grand-Archives/Elden-Ring-CT-TGA#73]
I was eagerly awaiting the 1.11 update so that I could give myself individual duplicate Weapons instead of using MassItemGib.

I set the Reinforcement level to +25/+10 just like normal.

The first Weapon I added came out as a +25 Somber Weapon: The Greatsword of Damnation.

If I hadn't double-checked that the Weapon was Somber I expect this could have resulted in an Online Ban even while trying to use CE properly and in good-faith.

I didn't check any other Weapons, but I doubt the Bug is isolated to only that Weapon.

(This happened with the .1 Bug-Fix update that was released an hour after the initial 1.11 update.)

**Comment by inuNorii** [comment]
Thanks for mentioning this so quickly, I re-released the version with a quick temporary solution while I solve it properly.

**Comment by ZINK-ZINK** [comment]
No problem, thanks for bandaid fixing it so quickly. 

I Discarded the Bugged Weapons immediately, but I didn't reset/restore my Save File, there aren't any weird item Flags that will remain and get me Banned for obtaining a +25 Somber are there? ie as long as I didn't go online with the Bugged weapon I should be safe right?

**Comment by inuNorii** [comment]
As long as you don't equip them or have them equipped while online, you should be good!
I fixed it properly in v1.11.2, so it should be fast again as well.
