### ISSUE TITLE
Event tab not opening upon click 

### ISSUE THREAD

**Issue by TeikoMaffia** [The-Grand-Archives/Elden-Ring-CT-TGA#75]
When I click the "Event" tab, it doesn't open even when I restarted the table. 

I am running on Cheat Engine 7.4

**Comment by Courageousodin** [comment]
Also having this issue with v1.11.2 of the cheat table, version 7.5 cheat engine. everything else opens fine but can't open the event flags record.

**Comment by MrEldenRing** [comment]
I am also having the same issue, right clicking the "Event Flags" tab comes up with an error saying <<The array of byte named ef.get_call could not be found>>

**Comment by SrKibo** [comment]
Same issue here:
CT version 1.11.2
CE version 7.5

**Comment by MrEldenRing** [comment]
Hey all, Im not sure if you are using any mods, but I found that the event tab wont open with the mod Glorious Merchant installed, removing the mod and loading up ER with Mod Engine 2 lets me access the events tab with no issues, not sure why this mod is causing some issues but that has fixed it on my end.

**Comment by Courageousodin** [comment]
Hello, I've found a solution to my issue. It seems using the cheat table on a seamless co-op installation of elden ring was the issue. Given what MrEldenRing's issue was, its possible all of our issues could be trying to use the cheat table on a modded version of elden ring.
