### ISSUE TITLE
Seamless COOP removal of items doesn't work anymore

### ISSUE THREAD

**Issue by Entixs** [The-Grand-Archives/Elden-Ring-CT-TGA#76]
After the modder updated the mod to work with the DLC... The removal of items script does not work anymore but I did do a dive into what the new item IDs are and these are the new item IDs and I did test on removing them and they do disappear.
Only way I saw removing them was from the inventory idx number. I could not remove them via item ID for whatever reason.
![Seamless coop item ids](https://github.com/The-Grand-Archives/Elden-Ring-CT-TGA/assets/66260102/6757118c-75da-4ef1-b2a7-10795cf60365)

**Comment by inuNorii** [comment]
Thanks, I'll add them to the script.
They need to be converted to hex and have 0x40000000 added to get the actual IDs that can be used.
