### ISSUE TITLE
Heeeeelp the table doesnt work, maybe, I dontk know

### ISSUE THREAD

**Issue by GerPapasito99** [The-Grand-Archives/Elden-Ring-CT-TGA#77]
Good afternoon.

I don't know what I'm doing wrong, the table doesn't work for me.

1. I am in the ERShofET DLC in the first grace
2. I have the cheat engine version 7.5
3. I went to your page
https://github.com/The-Grand-Archives/Elden-Ring-CT-TGA/releases/tag/v1.11.2

and download the 3 files

4. The first contains the table and the appid that I put in the following address
D:\SteamLibrary\steamapps\common\ELDEN RING\Game

5. I DON'T KNOW what to do with the other 2 files on your page or where to paste them
- Elden-Ring-CT-TGA-1.11.2
- Elden-Ring-CT-TGA-1.11.2.tar

6. Open the Game then open the Cheat Engine, load the ER_TGA_v1.11.2 table,

7. I click on statistics, I get my level, etc... When I click on build creation, I click on master gib, I select the DLC weapons option, Talismans, armor, etc...
It does NOT select anything for me, nor does it give me anything.

Help

**Comment by tremwil** [comment]
The two other files are the source code of this repository. You don't need them to use the table.

As for the cheat table itself, can you explain what you mean by "it does not *select* anything for me?" If the script doesn't appear to do anything, right click on its description after trying to activate it. At the top of the context menu you should see an error message. Please post it here so we can investigate further.

**Comment by GerPapasito99** [comment]
Hello Friend good afternoon.

Thanks for replying, it's good to know that the files name:
- Elden-Ring-CT-TGA-1.11.2
- Elden-Ring-CT-TGA-1.11.2.tar
I do not need them.

Well I'll explain to you, as I mentioned previously in step 7...
I click on Item Gib
I select Item
I select for example Black knife
Reinforced to +10/+25
And in theory I should hit Spawn Item and at that moment, like the previous tables, the knife should appear but it won't let me mark the box, in fact it doesn't get marked, nothing happens no matter how many clicks I give.

Now, in the Spawn Item section, on the right it says Script, I click on it and the following appears:

1[ENABLE]
2{$lua}
3if syntaxcheck then return end
4local id = readInteger(item_menu + 0)
5local quantity = readInteger(item_menu + 4)
6local reinforceLv = readByte(item_menu + 10)
7local upgrade = readSmallInteger(item_menu + 8)
8local gem = readInteger(item_menu + 12)
9
10ItemGive(id, quantity, reinforceLv, upgrade, gem)
11disableMemrec(memrec)
12[DISABLE]


Now, I go down and click on Marter gib
I click on gib all weapons and it doesn't let me check the box and nothing happens, even further down is the weapons section of the DLC, I proceed to check the box, and nothing... I do the same, I click on Script and I The list of all weapons appears and the following appears at the bottom:

ItemGive(items)
disableMemrec(memrec)
[DISABLE]

I don't know what to do anymore... it doesn't go from there

**Comment by tremwil** [comment]
Can you do what I asked in my previous comment? Based on what you said it seems the script is throwing an error somewhere, but I can't help you unless I know where.
