### ISSUE TITLE
Mass Item Gib Question & Missing Items

### ISSUE THREAD

**Issue by CerezaKitty** [The-Grand-Archives/Elden-Ring-CT-TGA#79]
- Why are these items not in the mass gib? I always have to give them to myself manually, so far It's been months and I haven't gotten banned once for that and I'm pretty sure It's safe to give them to yourself.

- Pots & Others
Cracked Pot - 20
Ritual Pot - 10
Perfume Bottle - 10
Memory Stone - 8
Larval Tear - 99 [Base game version]

- Re-usable Items
Mimic's Veil
Wraith Calling Bell
Lantern
Omen Bairn
Regal Omen Bairn
Ancestral Infant's Head
Margit's Shackle
Mohg's Shackle
Blasphemous Claw

- Missing Items from the DLC Misc cosumables
Sunwarmth Stone
Glinting Nail
Fire Spritestone
Fire Coil
Golden Vow [Item Form]
Surging Frenzied Flame
Call of Tibia
Perfumed Oil of Ranah
Horned Bairn
Spritestone
Bondstone
Prattling Pate Lamentation

**Comment by inuNorii** [comment]
If I recall correctly, in the previous version of ItemGib there was reason to not have items in MassItemGib that would be limited like these. Looks like I'll be adding a script for these now though, thank you for the reminder.

**Comment by CerezaKitty** [comment]
I'm not sure about the multiplayer items, if possible too, would be great, thanks!
