### ISSUE TITLE
cannot spawn items with itemgib/massitemgib

### ISSUE THREAD

**Issue by notsus0909** [The-Grand-Archives/Elden-Ring-CT-TGA#80]
i cannot check the boxes to give me items. i have the error <<Lua error in the script at line 2:[string "local syntaxcheck,memrec=... ..."]:79: invalid inventory>>

**Comment by inuNorii** [comment]
There is currently a little mistake in ItemGib's code, but your storage and/or inventory is full as well.

**Comment by notsus0909** [comment]
> There is currently a little mistake in ItemGib's code, but your storage and/or inventory is full as well.

would it help to discard items and then attempt again? or do i just wait for the updated code?

**Comment by inuNorii** [comment]
Cleaning up your storage should get around this error. You can have up to 1920 items in your storage.

**Comment by notsus0909** [comment]
> Cleaning up your storage should get around this error. You can have up to 1920 items in your storage.

cleaning up my storage worked. thank you for the quick help. have a blessed day!
