### ISSUE TITLE
You version of ER 2.0.2.3. might not be supported...

### ISSUE THREAD

**Issue by darkvvvnet** [The-Grand-Archives/Elden-Ring-CT-TGA#81]
![err ce](https://github.com/The-Grand-Archives/Elden-Ring-CT-TGA/assets/166164828/dfcfa4ba-16e1-4a91-bd8f-d501dd128999)

**Comment by darkvvvnet** [comment]
do I have to wait for update?

**Comment by inuNorii** [comment]
Most parts of the table should work, but some that rely on specific addresses won't.
The scripts that don't should inform you when you try to use them.

**Comment by darkvvvnet** [comment]
Ok. Thx!
