### ISSUE TITLE
Add/remove item quantity 

### ISSUE THREAD

**Issue by Weiss99** [The-Grand-Archives/Elden-Ring-CT-TGA#84]
Super easy question
Just wanna know where to go to change item quantity.
I know there is a last selected item script, but in there, there's only the options for max quantity possible in inventory/storage and not an option for the amount you currently have
So...
Just wanna know how to change this
(sry if this is the wrong place to ask
Believe it or not i didn't find a comment section
And thx in advance)

**Comment by inuNorii** [comment]
Hero -> EquipInventoryData could be used for this, though it's not the most user friendly.

Alternative features I can suggest are
- ItemGib, lets you acquire items with any quantity you want
- RemoveItem, lets you delete an item from your inventory entirely

Questions like this would go on our Discord server.

**Comment by Weiss99** [comment]
Hmmm
Does Removeitem allow you to remove things from storage too? Or is it strictly an inventory thing
Sry, can use it myself rn. Am not in home currently
