### ISSUE TITLE
Incorrect offsets in 1.12

### ISSUE THREAD

**Issue by Umgak** [The-Grand-Archives/Elden-Ring-CT-TGA#85]
In 1.12.1, these were off by +4, meaning they needed to be shifted by -4 to read accurate values. 1.13.0 shows that it fixed "Session Info equipment offsets" however they were shifted by an additional +4, and still show incorrect values. They need to now be shifted by -8 to be correct.

**Comment by Umgak** [comment]
A few other offsets are incorrect as well
Statistics -> Character - Level, ReinforceLv, and Health are all correct, but Focus and Stamina need a +4 (so Focus needs to be +148, Stamina +154)
Great Rune is also incorrect, should be [[[GameDataMan]+08]+528+98] now.

**Comment by inuNorii** [comment]
> Is there any reason it's listed as +528+98 and not just +5C0?
I usually write them how I see them referenced in the game's code or based on how the structures are laid out.
2B0+288+88 would now be how I'd write the updated offset for Great Rune.
```
[[GameDataMan]+8] = PlayerGameData
+2B0 = EquipGameData
...+288 = EquipItemData
...+88 = Great Rune offset
```
The game's code references the offsets like this, so I write them separated the same way.

**Comment by Umgak** [comment]
Ah, thanks for the explanation. I went ahead and changed it in my PR.
