### ISSUE TITLE
Not working with SeamlessCoop on Linux

### ISSUE THREAD

**Issue by colourjak** [The-Grand-Archives/Elden-Ring-CT-TGA#87]
I run Elden Ring through a steam shortcut to the SeamlessCoop launcher, which then launches Elden Ring. I have used protontricks to run cheat engine in the same prefix as the SeamlessCoop launcher. I can select the process for Elden Ring but when I try to enable to cheat table it throws an error and it doesn't work. Is there anything I can do about this?
![image](https://github.com/user-attachments/assets/3ef78c35-a9c5-46df-a85f-98174ebc540c)

**Comment by inuNorii** [comment]
If you can set it up, try `protonhax` instead.

**Comment by colourjak** [comment]
Protonhax won't work when using seamless for me

**Comment by inuNorii** [comment]
That's really strange, cause it works for me.

**Comment by colourjak** [comment]
`protonhax ls` returns 0 for me, and when I try running cheat engine, it says there isn't anything running with Elden Ring's appid. I have made sure to add it to my launch parameters, which are: 
`gamemoderun python er-patcher --rate 144 -uvcs -x ersc_launcher.exe -- env WINEFSYNC=1 WINEESYNC=1 MANGOHUD=1 DXVK_ASYNC=1 protonhax init %command%`

**Comment by inuNorii** [comment]
That sure is a lot of launch params.
![Screenshot_2024-07-18_12-15-35](https://github.com/user-attachments/assets/9546509b-f4aa-4e49-ab30-d244f7d7d43f)

**Comment by colourjak** [comment]
Still no luck trimming my parameters

**Comment by colourjak** [comment]
Since `protonhax ls` gave 0, I was able to run cheat engine with `protonhax start 0 /path/to/CheatEngine.exe`, using 0 instead of using Elden Ring's usual appid, 1245620.
