### ISSUE TITLE
Adding uplifting aromatics via ItemGib puts them into storage only and doesnt allow you to retrieve them

### ISSUE THREAD

**Issue by natemvm-py** [The-Grand-Archives/Elden-Ring-CT-TGA#99]
When using the cheat table to acquire uplifting aromatics via the ItemGib they go straight into the storage chest as if ive got too many in my inventory even thought I have none. When I go to retrieve them from my chest it just says "Unable to retrieve item. Inventory is full". Even though I started a brand new player and only spawned in the uplifting aromatics to test, and it still says my inventory is full? Unsure if this is a cheat table specific issue or something else im missing in-game.

**Comment by Sage420b** [comment]
you don't have perfume bottles "which are used to store aromatics", i've already opened an issue but was closed imediatly by author...because those cannot be dropped using itemgib
